
name: Build

on: [push, pull_request]

jobs:

  build:
    strategy:
        fail-fast: false
        matrix:
          os: [ windows ]
    runs-on: ${{ matrix.os }}-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on


    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: build and test
      run: dotnet test
